version: "3"
services:
  taskify:
    image: therealghostdev/taskify:latest
    volumes:
      - "./:/usr/src/taskify"
      - "./config/firebase/secret/taskify-29c1e-firebase-adminsdk-lnsvf-3b40d04243.json:/usr/src/taskify/config/firebase/secret/taskify-29c1e-firebase-adminsdk-lnsvf-3b40d04243.json"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      MONGODB_URI: ${MONGODB_URI}
      REDIS_URL: ${REDIS_URL}
      NODE_ENV: development
      GOOGLE_APPLICATION_CREDENTIALS: /usr/src/taskify/config/firebase/secret/taskify-29c1e-firebase-adminsdk-lnsvf-3b40d04243.json

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
